# Generated by Django 4.2 on 2023-05-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fundmodel',
            table='Laporan',
        ),
    ]
