# Generated by Django 4.2 on 2023-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_remove_fundmodel_kategori_alter_fundmodel_jumlah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmodel',
            name='Catatan',
            field=models.TextField(blank=True),
        ),
    ]
